language: python
python:
  - "2.7"

services:
  - postgresql
  - redis-server

before_script:
  - psql -c "CREATE ROLE adminbuy WITH PASSWORD 'adminbuy' NOSUPERUSER CREATEDB NOCREATEROLE LOGIN;" -U postgres
  - psql -c "CREATE DATABASE adminbuy WITH OWNER=adminbuy TEMPLATE=template0 ENCODING='utf-8';" -U postgres

install:
  - pip install -r REQUIREMENTS

script:
 - python -m unittest discover