language: python
python:
  - "2.7"

services:
  - postgresql

before_script:
  - psql -c 'create role test;' -U postgres

install:
  - pip install -r REQUIREMENTS

script:
 - python -m unittest discover