language: python
python:
  - "2.7"

services:
  - postgresql9.3
  - redis-server

before_script:
  - psql -c "CREATE ROLE adminbuy WITH PASSWORD 'adminbuy' NOSUPERUSER CREATEDB NOCREATEROLE LOGIN;"
  - psql -c "CREATE DATABASE adminbuy WITH OWNER=adminbuy TEMPLATE=template0 ENCODING='utf-8';"

install:
  - pip install -r REQUIREMENTS

script:
 - python -m unittest discover