"""empty message

Revision ID: 12eda9ed526b
Revises: 548ef7474d22
Create Date: 2015-04-13 12:35:41.022949

"""

# revision identifiers, used by Alembic.
revision = '12eda9ed526b'
down_revision = '548ef7474d22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('datetime2', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'datetime2')
    ### end Alembic commands ###
