"""empty message

Revision ID: 130d74c14470
Revises: 4f55a3c62dc6
Create Date: 2015-09-21 13:14:51.082388

"""

# revision identifiers, used by Alembic.
revision = '130d74c14470'
down_revision = '4f55a3c62dc6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('deviceId', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_item_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sync_id'], ['sync_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_item_session')
    op.drop_table('sync_session')
    ### end Alembic commands ###
