"""empty message

Revision ID: 1332f494db71
Revises: 992ea3927bb
Create Date: 2015-04-08 20:17:15.045590

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.sqlite.pysqlite import SQLiteDialect_pysqlite

revision = '1332f494db71'
down_revision = '992ea3927bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('way_bill_return', sa.Column('returninst_id', sa.Integer(), nullable=True))
    bind = op.get_bind()

    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.drop_constraint(u'way_bill_return_return_id_fkey', 'way_bill_return', type_='foreignkey')
        except Exception as exc:
            pass
    else:
        op.drop_constraint(u'way_bill_return_return_id_fkey', 'way_bill_return', type_='foreignkey')




    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.create_foreign_key(None, 'way_bill_return', 'return', ['returninst_id'], ['id'])
        except Exception as exc:
            pass
    else:
        op.create_foreign_key(None, 'way_bill_return', 'return', ['returninst_id'], ['id'])

    # op.create_foreign_key(None, 'way_bill_return', 'return', ['returninst_id'], ['id'])
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.drop_column('way_bill_return', 'return_id')
        except Exception as exc:
            pass
    else:
        op.drop_column('way_bill_return', 'return_id')


    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.drop_constraint(u'way_bill_return_items_waybill_id_fkey', 'way_bill_return_items', type_='foreignkey')
        except Exception as exc:
            pass
    else:
        op.drop_constraint(u'way_bill_return_items_waybill_id_fkey', 'way_bill_return_items', type_='foreignkey')


    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.create_foreign_key(None, 'way_bill_return_items', 'way_bill_return', ['waybill_id'], ['id'])
        except Exception as exc:
            pass
    else:
        op.create_foreign_key(None, 'way_bill_return_items', 'way_bill_return', ['waybill_id'], ['id'])

    # op.create_foreign_key(None, 'way_bill_return_items', 'way_bill_return', ['waybill_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'way_bill_return_items', type_='foreignkey')
    op.create_foreign_key(u'way_bill_return_items_waybill_id_fkey', 'way_bill_return_items', 'way_bill', ['waybill_id'], ['id'])
    op.add_column('way_bill_return', sa.Column('return_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'way_bill_return', type_='foreignkey')
    op.create_foreign_key(u'way_bill_return_return_id_fkey', 'way_bill_return', 'return', ['return_id'], ['id'])
    op.drop_column('way_bill_return', 'returninst_id')
    ### end Alembic commands ###
