"""empty message

Revision ID: 1577ba434520
Revises: 16e4bf34ee36
Create Date: 2015-04-03 12:19:53.246010

"""

# revision identifiers, used by Alembic.
revision = '1577ba434520'
down_revision = '16e4bf34ee36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_item', sa.Column('price_gross', sa.DECIMAL(), nullable=True))
    op.add_column('invoice_item', sa.Column('price_retail', sa.DECIMAL(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_item', 'price_retail')
    op.drop_column('invoice_item', 'price_gross')
    ### end Alembic commands ###
