"""empty message

Revision ID: 26c14dc2ce0b
Revises: 320891391dd
Create Date: 2015-03-31 10:09:11.406151

"""

# revision identifiers, used by Alembic.
revision = '26c14dc2ce0b'
down_revision = '320891391dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acceptance', sa.Column('type', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acceptance', 'type')
    ### end Alembic commands ###
