"""empty message

Revision ID: 2c039d879342
Revises: 43e0d08684bf
Create Date: 2015-03-20 15:31:25.534942

"""

# revision identifiers, used by Alembic.
revision = '2c039d879342'
down_revision = '43e0d08684bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('way_bill', sa.Column('status', sa.SmallInteger(), nullable=True))
    # sa.Column('status', sa.SmallInteger(), nullable=True),
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('way_bill', 'status')
    ### end Alembic commands ###
