"""empty message

Revision ID: 2fec482c8e85
Revises: 478fc7cc5139
Create Date: 2015-04-08 13:04:40.930381

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.sqlite.pysqlite import SQLiteDialect_pysqlite

revision = '2fec482c8e85'
down_revision = '478fc7cc5139'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('return_id', sa.Integer(), nullable=True))

    bind = op.get_bind()
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.create_foreign_key(None, 'mails', 'return', ['return_id'], ['id'])
        except Exception as exc:
            pass
    else:
        op.create_foreign_key(None, 'mails', 'return', ['return_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mails', type_='foreignkey')
    op.drop_column('mails', 'return_id')
    ### end Alembic commands ###
