"""empty message

Revision ID: 314046672234
Revises: 12eda9ed526b
Create Date: 2015-04-13 12:38:42.642197

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.sqlite.pysqlite import SQLiteDialect_pysqlite

revision = '314046672234'
down_revision = '12eda9ed526b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.drop_column('inventory', 'datetime')
        except Exception as exc:
            pass
    else:
        op.drop_column('inventory', 'datetime')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
