"""empty message

Revision ID: 320891391dd
Revises: 46170ac4b436
Create Date: 2015-03-30 12:51:24.864971

"""

# revision identifiers, used by Alembic.
revision = '320891391dd'
down_revision = '46170ac4b436'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acceptance_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acceptance_id', sa.Integer(), nullable=True),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acceptance_id'], ['acceptance.id'], ),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acceptance_items')
    ### end Alembic commands ###
