"""empty message

Revision ID: 347063b3e6f3
Revises: b9d2e175e60
Create Date: 2015-04-06 17:18:05.979986

"""

# revision identifiers, used by Alembic.
revision = '347063b3e6f3'
down_revision = 'b9d2e175e60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rate_retail', sa.DECIMAL(), nullable=True),
    sa.Column('rate_gross', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    ### end Alembic commands ###
