"""empty message

Revision ID: 394f6e9df9ed
Revises: 3b672be254df
Create Date: 2015-03-02 10:22:49.243350

"""

# revision identifiers, used by Alembic.
revision = '394f6e9df9ed'
down_revision = '3b672be254df'

from alembic import op
import sqlalchemy as sa
# from sqlalchemy_utils.types.choice import ChoiceType
# sa.ChoiceType = ChoiceType



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=250), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('of', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['point_sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_items')
    op.drop_table('inventory')
    ### end Alembic commands ###
