"""empty message

Revision ID: 39b4e0d6bda3
Revises: 51b355b10383
Create Date: 2015-08-10 16:11:42.539396

"""

# revision identifiers, used by Alembic.
revision = '39b4e0d6bda3'
down_revision = '51b355b10383'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    ### end Alembic commands ###
