"""empty message

Revision ID: 40abc5e3e07
Revises: 46d10cc68d45
Create Date: 2015-04-09 14:46:58.779274

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.sqlite.pysqlite import SQLiteDialect_pysqlite

revision = '40abc5e3e07'
down_revision = '46d10cc68d45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('files', sa.String(), nullable=True))
    op.add_column('mails', sa.Column('text', sa.String(), nullable=True))

    bind = op.get_bind()
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.drop_column('mails', 'file')
        except Exception as exc:
            pass
    else:
        op.drop_column('mails', 'file')


    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mails', 'text')
    op.drop_column('mails', 'files')
    ### end Alembic commands ###
