"""empty message

Revision ID: 4644bccd8535
Revises: 4105da2ed54c
Create Date: 2015-09-11 18:44:05.439545

"""

# revision identifiers, used by Alembic.
revision = '4644bccd8535'
down_revision = '4105da2ed54c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    ### end Alembic commands ###
