# coding: utf-8
"""empty message

Revision ID: 4d9a2f4596d5
Revises: 349f908b69cd
Create Date: 2015-11-17 12:53:43.399175

"""

# revision identifiers, used by Alembic.
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship, backref
from sqlalchemy_utils import ChoiceType

revision = '4d9a2f4596d5'
down_revision = '349f908b69cd'

from alembic import op
import sqlalchemy as sa

Session = sessionmaker()

Base = declarative_base()


class Invoice(Base):
    __tablename__ = 'invoice'
    id = sa.Column(sa.Integer(), primary_key=True)


class AI(Base):
    __tablename__ = 'linkacceptanceinvoice'

    acceptance_id = sa.Column(sa.Integer(), sa.ForeignKey('acceptance.id'), primary_key=True)
    invoice_id = sa.Column(sa.Integer(), sa.ForeignKey('invoice.id'), primary_key=True)


class Acceptance(Base):
    __tablename__ = 'acceptance'
    id = sa.Column(sa.Integer, primary_key=True)
    # # Накладная основание
    invoice_id = sa.Column(sa.Integer, sa.ForeignKey('invoice.id'), unique=True)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    session = Session(bind=bind)

    for acceptance in session.query(Acceptance).all():
        link = AI(acceptance_id=acceptance.id, invoice_id=acceptance.invoice_id)
        acceptance.invoice_id = None
        session.add(link)
        session.add(acceptance)

    session.commit()
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    for lnk in session.query(AI).all():

        acceptance = session.query(Acceptance).get(
            lnk.acceptance_id
        )

        acceptance.invoice_id = lnk.invoice_id

        session.delete(lnk)
        session.add(acceptance)
    session.commit()
    ### end Alembic commands ###
