"""empty message

Revision ID: 51b355b10383
Revises: 199a75abab41
Create Date: 2015-07-31 20:08:47.990084

"""

# revision identifiers, used by Alembic.
revision = '51b355b10383'
down_revision = '199a75abab41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("mails", "date", type_=sa.types.DateTime(timezone=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
