"""empty message

Revision ID: 548ef7474d22
Revises: 2c2254f46b3a
Create Date: 2015-04-10 13:42:05.178259

"""

# revision identifiers, used by Alembic.
revision = '548ef7474d22'
down_revision = '2c2254f46b3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('return', sa.Column('status', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return', 'status')
    op.drop_column('return', 'date')
    ### end Alembic commands ###
