"""empty message

Revision ID: 992ea3927bb
Revises: 2fec482c8e85
Create Date: 2015-04-08 18:16:08.216119

"""

# revision identifiers, used by Alembic.
revision = '992ea3927bb'
down_revision = '2fec482c8e85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('way_bill_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=250), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('pointsale_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('typeRec', sa.SmallInteger(), nullable=True),
    sa.Column('return_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['pointsale_id'], ['point_sale.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['receiver.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['return.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('way_bill_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waybill_id', sa.Integer(), nullable=True),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.Column('count_plan', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], ),
    sa.ForeignKeyConstraint(['waybill_id'], ['way_bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('way_bill_return_items')
    op.drop_table('way_bill_return')
    ### end Alembic commands ###
