"""empty message

Revision ID: e1b5bef2a9fc
Revises: 395365dd69f3
Create Date: 2016-12-16 20:44:27.616804

"""

# revision identifiers, used by Alembic.
revision = 'e1b5bef2a9fc'
down_revision = '395365dd69f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ware_house')
    op.drop_table('retail_invoice_item')
    op.drop_table('retail_invoice')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retail_invoice_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('retailinvoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('good_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['good_id'], [u'good.id'], name=u'retail_invoice_item_good_id_fkey'),
    sa.ForeignKeyConstraint(['retailinvoice_id'], [u'retail_invoice.id'], name=u'retail_invoice_item_retailinvoice_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'retail_invoice_item_pkey')
    )
    op.create_table('retail_invoice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], [u'invoice.id'], name=u'retail_invoice_invoice_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'retail_invoice_pkey')
    )
    op.create_table('ware_house',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'ware_house_pkey')
    )
    ### end Alembic commands ###
