version: '3'
services:
  buyapi_nginx:
    image: nginx:latest
    volumes:
      - ../config/:/etc/nginx/conf.d/
      - static_volume:/code/static
      - media_volume:/code/media
      - docker_homecrm_media_volume:/code/media_homecrm
    ports:
      - 127.0.0.1:8100:80
    depends_on:
      - buyapi_web
  buyapi_web:
    image: buyapi:1.0
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/code
      - static_volume:/code/static
      - media_volume:/code/media
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure

volumes:
  docker_homecrm_media_volume:
    external: true
  media_volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/media
      o: bind
  static_volume: {}