version: '3'
services:
  buyapi_nginx:
    image: nginx:latest
    volumes:
      - ../config/:/etc/nginx/conf.d/
      - static_volume:/code/staticd
      - media_volume:/code/mediad
      - docker_homecrm_media_volume:/code/media_homecrm
    ports:
      - 127.0.0.1:8100:80
    depends_on:
      - buyapi_web
  buyapi_web:
    image: buyapi:1.0
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/code
      - static_volume:/code/staticd
      - media_volume:/code/mediad

volumes:
  docker_homecrm_media_volume:
    external: true
  static_volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/static
      o: bind
  media_volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/static
      o: bind
