"""empty message



Revision ID: 140ce94a8336

Revises: 2c039d879342

Create Date: 2015-03-21 23:04:22.612000



"""



# revision identifiers, used by Alembic.

revision = '140ce94a8336'

down_revision = '2c039d879342'



from alembic import op

import sqlalchemy as sa





def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('way_bill', sa.Column('typeRec', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###





def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('way_bill', 'typeRec')
    ### end Alembic commands ###

