"""empty message

Revision ID: 16e4bf34ee36
Revises: 259abe9a78c3
Create Date: 2015-04-01 10:58:54.727656

"""

# revision identifiers, used by Alembic.
revision = '16e4bf34ee36'
down_revision = '259abe9a78c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acceptance_items', sa.Column('fact_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acceptance_items', 'fact_count')
    ### end Alembic commands ###
