"""empty message

Revision ID: 199a75abab41
Revises: 314046672234
Create Date: 2015-04-13 12:39:03.675562

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.sqlite.pysqlite import SQLiteDialect_pysqlite

revision = '199a75abab41'
down_revision = '314046672234'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('datetimenew', sa.DateTime(timezone=True), nullable=True))
    bind = op.get_bind()
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.drop_column('inventory', 'datetime2')
        except Exception as exc:
            pass
    else:
        op.drop_column('inventory', 'datetime2')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('datetime2', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('inventory', 'datetimenew')
    ### end Alembic commands ###
