"""empty message

Revision ID: 259abe9a78c3
Revises: eaa90a370dc
Create Date: 2015-03-31 17:11:48.566974

"""

# revision identifiers, used by Alembic.
revision = '259abe9a78c3'
down_revision = 'eaa90a370dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acceptance', sa.Column('status', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acceptance', 'status')
    ### end Alembic commands ###
