"""empty message

Revision ID: 2ee0a4b92671
Revises: 4c536f7bdb1e
Create Date: 2015-10-09 12:56:37.858067

"""

# revision identifiers, used by Alembic.
revision = '2ee0a4b92671'
down_revision = '4c536f7bdb1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collect', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'collect_seller_id_fkey', 'collect', type_='foreignkey')
    op.create_foreign_key(None, 'collect', 'user', ['user_id'], ['id'])
    op.drop_column('collect', 'seller_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collect', sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'collect', type_='foreignkey')
    op.create_foreign_key(u'collect_seller_id_fkey', 'collect', 'seller', ['seller_id'], ['id'])
    op.drop_column('collect', 'user_id')
    ### end Alembic commands ###
