"""empty message

Revision ID: 4105da2ed54c
Revises: 39b4e0d6bda3
Create Date: 2015-09-11 18:40:37.728813

"""

# revision identifiers, used by Alembic.
revision = '4105da2ed54c'
down_revision = '39b4e0d6bda3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column(u'user', 'login',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'user', 'login',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_table('role')
    ### end Alembic commands ###
