"""empty message

Revision ID: 43e0d08684bf
Revises: 1d4e877b8561
Create Date: 2015-03-06 13:47:21.021691

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.sqlite.pysqlite import SQLiteDialect_pysqlite

revision = '43e0d08684bf'
down_revision = '1d4e877b8561'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('count_after', sa.Integer(), nullable=True))
    op.add_column('inventory_items', sa.Column('count_before', sa.Integer(), nullable=True))
    op.add_column('inventory_items', sa.Column('good_id', sa.Integer(), nullable=True))
    bind = op.get_bind()
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.create_foreign_key(None, 'inventory_items', 'good', ['good_id'], ['id'])
        except Exception as exc:
            pass
    else:
        op.create_foreign_key(None, 'inventory_items', 'good', ['good_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.drop_constraint(None, 'inventory_items', type_='foreignkey')
        except Exception as exc:
            pass
    else:
        op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'good_id')
    op.drop_column('inventory_items', 'count_before')
    op.drop_column('inventory_items', 'count_after')
    ### end Alembic commands ###
