"""empty message

Revision ID: 46d10cc68d45
Revises: 1332f494db71
Create Date: 2015-04-09 12:37:50.025145

"""

# revision identifiers, used by Alembic.
revision = '46d10cc68d45'
down_revision = '1332f494db71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('sum', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['point_sale.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collect')
    ### end Alembic commands ###
