"""empty message

Revision ID: 4c536f7bdb1e
Revises: 130d74c14470
Create Date: 2015-09-25 16:07:18.573043

"""

# revision identifiers, used by Alembic.
revision = '4c536f7bdb1e'
down_revision = '130d74c14470'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime_start', sa.DateTime(), nullable=True),
    sa.Column('datetime_end', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('sync_start_id', sa.Integer(), nullable=True),
    sa.Column('sync_end_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sync_end_id'], ['sync_session.id'], ),
    sa.ForeignKeyConstraint(['sync_start_id'], ['sync_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'sync_item_session', sa.Column('workday_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sync_item_session', 'work_day', ['workday_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_item_session', type_='foreignkey')
    op.drop_column(u'sync_item_session', 'workday_id')
    op.drop_table('work_day')
    ### end Alembic commands ###
