"""empty message

Revision ID: 52dd9e57867
Revises: 347063b3e6f3
Create Date: 2015-04-07 11:53:00.065116

"""

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.sqlite.pysqlite import SQLiteDialect_pysqlite

revision = '52dd9e57867'
down_revision = '347063b3e6f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mails', sa.Column('order_id', sa.Integer(), nullable=True))
    bind = op.get_bind()
    if type(bind.dialect) == SQLiteDialect_pysqlite:
        try:
            op.create_foreign_key(None, 'mails', 'order', ['order_id'], ['id'])
        except Exception as exc:
            pass
    else:
        op.create_foreign_key(None, 'mails', 'order', ['order_id'], ['id'])
    # op.create_foreign_key(None, 'mails', 'order', ['order_id'], ['id'])
    op.add_column('order_item', sa.Column('full_name', sa.String(length=250), nullable=True))
    op.add_column('order_item', sa.Column('number_global', sa.String(length=250), nullable=True))
    op.add_column('order_item', sa.Column('number_local', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'number_local')
    op.drop_column('order_item', 'number_global')
    op.drop_column('order_item', 'full_name')
    op.drop_constraint(None, 'mails', type_='foreignkey')
    op.drop_column('mails', 'order_id')
    ### end Alembic commands ###
