"""empty message

Revision ID: b9d2e175e60
Revises: 1577ba434520
Create Date: 2015-04-06 16:42:37.752259

"""

# revision identifiers, used by Alembic.
revision = 'b9d2e175e60'
down_revision = '1577ba434520'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
